### ISSUE TITLE
Fix issue in medication toggle icon animation

### ISSUE THREAD

**Issue by ndrong** [RUGSoftEng/2018-Tuberculosis-iOS#67]
When switching days, identical `DosageItem`s with differing statuses start their icon animations.

**Comment by juliusvdijk** [comment]
Moet ik het weer fixen 😉 ? @NDrong

**Comment by ndrong** [comment]
Zal deze morgen of overmorgen ff fixen ;)

**Comment by ndrong** [comment]
Resolved in #69.
